### ISSUE TITLE
add dew point from old library

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_BME280#11]
handy code, lets recycle! https://github.com/adafruit/Adafruit_Python_BME280/pull/20

@kattni this is a good one for ya, you can test on a microcontroller (no need to use pi even tho original library was for pi), do it for celsius only, skip the _f version

**Comment by kattni** [comment]
Added and tested! I'll update the example to include it as well.

**Comment by kattni** [comment]
Done!

**Comment by kattni** [comment]
Build and PyPi deployment successful.
