### ISSUE TITLE
needs oversampling + IIR Filter options

### ISSUE THREAD

**Issue by jonas87** [adafruit/Adafruit_CircuitPython_BME280#21]
If I use this library and keep a log of the measurements, the temperature and humidity data are super noisy.
I tried different measurements intervals in the range [2;120] seconds, but all of it is noisy. The pressure data on the other hand is smooth. 

The BME280 has support for supersampling and has a built in IIR filter, both of which help smoothing out the data. Currently the library only has supersampling enabled for humidity (hardcoded), it would be useful if the value can be set, and also for temperature and pressure. The IIR filter currently does not seem to be used?

![screenshot 2019-02-12 at 10 11 12](https://user-images.githubusercontent.com/28352952/52625456-544e0880-2eb1-11e9-80bd-cee89a8016ae.png)

**Comment by ladyada** [comment]
correct! if you'd like to try enabling that oversampling support and submitting a PR we'd be psyched to add it :)

**Comment by makermelissa** [comment]
Fixed with #22.
