### ISSUE TITLE
change I2c-address/ read two sensors

### ISSUE THREAD

**Issue by braini1511** [adafruit/Adafruit_CircuitPython_BME280#24]
Hi there,

is there any chance to read out two BME280 with your library? What would be needed to be changed?

best regards
René

**Comment by deshipu** [comment]
Just specify the I2C address or SPI CS pin for each of the sensors when creating the sensor object.

**Comment by caternuson** [comment]
For I2C you also need to make a hardware change to set the address:

> By default, the i2c address is 0x77.  If you add a jumper from SDO to GND, the address will change to 0x76.
