### ISSUE TITLE
Don't use frozenset

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_BME280#25]
not included on small CP boards :)

**Comment by tannewt** [comment]
We should replace them with tuples.

**Comment by loganwedwards** [comment]
Is this related to not being able to use the BME 280 with the Feather M0 RFM9x. I am using the provided sample code from the tutorials and this is where it fails.
```bash
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Press any key to enter the REPL. Use CTRL-D to reload.soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
main.py output:
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "adafruit_bme280.py", line 77, in <module>
NameError: name 'frozenset' is not defined
```
Is there a way to have CircuitPython + Feather M0 + BME280 work in harmony, e.g., use an older release?

**Comment by loganwedwards** [comment]
With further research, it appears PR #26 will address this.
