### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by safariace** [adafruit/Adafruit_CircuitPython_BME280#32]
Using a Sparkfun RedBoard T.

on import adafruit_bme280 get a Memory error.

in the REPL I get slightly more information but not much:

>>> import adafruit_bme280
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: memory allocation failed, allocating 512 bytes

I've stripped back to just the sample code for the BME280 so nothing else is in RAM.  RAM is 256K on this board.

**Comment by ladyada** [comment]
hi just tried it with a gemma m0 and it def gets to later. please follow this guide exactly
https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout/python-circuitpython-test
and make sure you are using the bundle mpy files for all libraries
for tech support please post up in the sparkfun forums too!
