### ISSUE TITLE
Instructions for GY-BMP280

### ISSUE THREAD

**Issue by GitHubIsToxic** [adafruit/Adafruit_CircuitPython_BME280#36]
The GY-BMP280 (GY-BM P/E 280) and a few other similar (non-Adafruit) BMP/BME 280 boards, use the 0x76 I2C address instead of 0x77. Some tutorials I found on the web instruct changing the  address in library source code. But it is trivial to make this Adafruit driver work out-of-the-box.

For example, in the 'Usage Example' code, just change this line:

`bme280 = adafruit_bme280.Adafruit_BME280_I2C(i2c)`

to this:

`bme280 = adafruit_bme280.Adafruit_BME280_I2C(i2c, address=0x76)`

Perhaps it would be useful to add these instructions?

**Comment by ladyada** [comment]
hi please submit a PR to the usage example and we'll review it :)
